[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm --prefix client ci',
  'npm --prefix server ci'
]

[phases.build]
cmds = [
  'npm --prefix client run build',
  'rm -rf dist',
  'mv client/dist dist'
]

[start]
cmd = 'node server/server.js'
